### ISSUE TITLE
Only installs for VS 2022

### ISSUE THREAD

**Issue by towel42-com** [perforce/P4VS#10]
The latest manifest change breaks the ability to install this for VS 2019 or VS 2017 which are still used dev systems.

Please at least make the previous versions downloadable, but this really should be fixed to support the previous versions

**Comment by skardile-perforce** [comment]
Hello, 

There is P4VS extension in 32 bit which supports VS 2019, 2017 & 2015. This github code might not provide direct support for it.

You can download it either directly from:
- Visual studio extension installer
- OR from the site https://marketplace.visualstudio.com/items?itemName=PerforceSoftware.P4VS-PerforcePluginforVisualStudio
- OR from perforce site selecting x86 build: https://www.perforce.com/downloads/helix-plugin-visual-studio-p4vs

**Comment by skardile-perforce** [comment]
A resolution answer has been provided on this issue on Feb 6th, 2023.

**Comment by skardile-perforce** [comment]
A resolution answer has been provided on this issue on Feb 6th, 2023.
