### ISSUE TITLE
Extension causing responsiveness issues inside Visual Studio

### ISSUE THREAD

**Issue by davkean** [perforce/P4VS#11]
Hey folks, I'm from the Visual Studio Performance and Reliability team and our telemetry has captured some performance problems with this extension in the wild.

It appears that under certain circumstances, the following stack performs an extraordinarly large amount of allocations, bringing Visual Studio to a crawl while the GC tries to clean up these allocations. 

We've caught the issue 3 times in the past 21 days, and at its worst is allocating over 1 GB/second. 

<HTML>
<BODY>
<TABLE><TR><TD>Name</TD></TR><TR><TD> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;+ mscorlib.ni!String.Concat</TD></TR><TR><TD> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;+ p4api.net!Perforce.P4.P4Exception..ctor(class System.String,class System.String[],class Perforce.P4.P4ClientErrorList,class Perforce.P4.P4ClientInfoMessageList)</TD></TR><TR><TD> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;+ p4api.net!P4Exception.Throw</TD></TR><TR><TD> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;+ p4api.net!P4Server.RunCommand</TD></TR><TR><TD> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;+ p4api.net!P4Command.RunInt</TD></TR><TR><TD> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;+ p4api.net!Perforce.P4.P4CommandResult..ctor(class Perforce.P4.P4Command,class Perforce.P4.StringList)</TD></TR><TR><TD> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;+ p4api.net!P4Command.Run</TD></TR><TR><TD> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;+ p4api.net!Repository.GetFileMetaData</TD></TR><TR><TD> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;+ p4vs_utils!P4ScmCache.UpdateFiles</TD></TR><TR><TD> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;+ p4vs_utils!P4ScmCache.RefreshFilesThreadProc</TD></TR></TABLE>

</BODY>
</HTML>

The issue appears to stem from [this line](https://github.com/perforce/p4api.net/blob/50f9a1f3fbc7cd8cb6ca19f63bd52467e7e7685b/p4api.net/P4Exception.cs#L268) in the exception's constructor where it looks like what is already likely a very large command-line is being concatenated to a large number of arguments. Each one of the new strings being created are larger than 85KB as I can see they are all being pushed on the [Large Object Heap](https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/large-object-heap). In one 60 second trace we automatically captured, this one loop produced 68 GB of allocations.

Please let me know if you need some help understanding/fixing this. We don't have a repro for this, as it was automatically captured by our telemetry system.

-Dave

**Comment by skardile-perforce** [comment]
Thanks @davkean for this insight. 

- To understand this further I just wanted to understand whether this problem occurs only when there is a situation for exceptions being raised? So that we can try to replicate with creating some exception situation. 

- And also what was the exception raised? Do you have any other inputs of logs etc.? (Reference for logging in P4VS - https://www.perforce.com/manuals/p4vs/Content/P4VS/intro.preferences.logging.html)

**Comment by davkean** [comment]
This will only occur when the constructor for P4Exception is called, which I assume is only created when that exception is being thrown.

Unfortunately, this has been caught by our performance telemetry on real customer machines and we don't capture enough information to see the contents of the exception, nor can we turn on logging on those machines. By looking at the code you can see that a very large command line with a large number of arguments will result in this problem.

**Comment by davkean** [comment]
I should add, all of these strings are ending up on the Large Object Heap (LOH), which requires an object allocation of 85 KB, which takes a string of 42,500 characters.

**Comment by skardile-perforce** [comment]
Okay. I will look for such a combination where this large command is formed.

**Comment by oold** [comment]
Anything being done about this issue? Seems like a matter of simply replacing the line concatenating the command arguments one by one with a `StringBuilder`. Could even pre-allocate the buffer since all the strings to be appended are already part of a collection.

**Comment by shraddhaborate** [comment]
This issue has been fixed for P4API.NET and will be available in next P4VS release.

**Comment by davkean** [comment]
Thanks @shraddhaborate and folks.
