### ISSUE TITLE
Add Visual Studio 2022 Support

### ISSUE THREAD

**Issue by jschroedl** [perforce/P4VS#2]
Visual Studio 2022 was recently released and is a 64-bit process now. This means that the existing P4VS does not work with it as it's a 32-bit plugin.  We need a 64-bit version of P4VS.

**Comment by Gav-Brown** [comment]
Yes please

**Comment by dvaghela** [comment]
If you are okay with the non-prod version of the extension:
You can download it from here: [Gituhub action](https://github.com/perforce/P4VS/actions/runs/1578828583)

Scroll to the bottom, download, and install the x64 bit version of the extension. 

P.S. I am not associated with the extension/perforce, so use it at your descration.

**Comment by dvaghela** [comment]
> Visual Studio 2022 was recently released and is a 64-bit process now. This means that the existing P4VS does not work with it as it's a 32-bit plugin. We need a 64-bit version of P4VS.

If you are okay with the non-prod version of the extension:
You can download it from here: [Github action workflow](https://github.com/perforce/P4VS/actions/runs/1578828583)

Scroll to the bottom, download, and install the x64 bit version of the extension. 

P.S. I am not associated with the extension/perforce, so use it at your discretion.

**Comment by Gav-Brown** [comment]
Perforce have just added VS2022 plugin to their website.
