### ISSUE TITLE
CodeLens links doesnt work in VS 2022

### ISSUE THREAD

**Issue by onovytskyi** [perforce/P4VS#5]
![image](https://user-images.githubusercontent.com/281254/150115177-7d6afa5c-54bc-4f8b-9d8f-e10f92d6f7a0.png)
Clicking one of the highlighted links in the CodeLens popup leads to an error below

```
---------------------------
Microsoft Visual Studio
---------------------------
Could not load file or assembly 'P4VS_Utils, Version=2020.2.222.4077, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
---------------------------
OK   
---------------------------
```
Plugin version 2020.2.222.4077
VS version 17.0.5

**Comment by ppiorunski** [comment]
Thanks for reporting it, It will be fixed in the next release. For now, the github actions non-production build is not affected by this issue.
